---
- name: Configure host.
  hosts: all

  vars_files:
    - default.config.yml
    - config.yml

  tasks:
    #- import_tasks: tasks/yay.yml
    #- import_tasks: tasks/intel.yml
    #- import_tasks: tasks/base-packages.yml
    #- import_tasks: tasks/shell.yml
    #- import_tasks: tasks/desktop-packages.yml
    #- import_tasks: tasks/sway.yml
    - import_tasks: tasks/nas-mounts.yml
