---
- name: Make sure directories exists
  vars:
    dir_mounts:
      - /mnt/nas/tank/
      - /mnt/nas/tank/downloads
      - /mnt/nas/tank/documents
      - /mnt/nas/tank/media/tv
      - /mnt/nas/tank/media/movies
  become: yes
  ansible.builtin.file:
    path: "{{ dir_mounts }}"
    state: directory

- name: Install cifs-utils
  become: true
  community.general.pacman:
    name: cifs-utils
    state: present

- name: Mount /mnt/nas/tank/downloads
  become: yes
  ansible.posix.mount:
    src: //10.100.0.4/downloads
    path: /mnt/nas/tank/downloads
    opts: "rw,credentials=/home/philip/dotfiles/env/.local/bin/smb,uid=1000,gid=1000"
    opts_no_log: false
    fstype: cifs
    state: mounted

- name: Mount /mnt/nas/tank/documents
  become: yes
  ansible.posix.mount:
    src: //10.100.0.4/documents
    path: /mnt/nas/tank/documents
    opts: "rw,credentials=/home/philip/dotfiles/env/.local/bin/smb,uid=1000,gid=1000"
    opts_no_log: false
    fstype: cifs
    state: mounted

- name: Mount /mnt/nas/tank/media/tv
  become: yes
  ansible.posix.mount:
    src: //10.100.0.4/tmp-tv
    path: /mnt/nas/tank/media/tv
    opts: "rw,credentials=/home/philip/dotfiles/env/.local/bin/smb,uid=1000,gid=1000"
    opts_no_log: false
    fstype: cifs
    state: mounted

- name: Mount /mnt/nas/tank/media/movies
  become: yes
  ansible.posix.mount:
    src: //10.100.0.4/tmp-movies
    path: /mnt/nas/tank/media/movies
    opts: "rw,credentials=/home/philip/dotfiles/env/.local/bin/smb,uid=1000,gid=1000"
    opts_no_log: false
    fstype: cifs
    state: mounted
